# permissions for end users to edit devfileregistries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devfileregistry-editor-role
rules:
- apiGroups:
  - registry.devfile.io
  resources:
  - devfileregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry.devfile.io
  resources:
  - devfileregistries/status
  verbs:
  - get
