# permissions for end users to view devfileregistries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devfileregistry-viewer-role
rules:
- apiGroups:
  - registry.devfile.io
  resources:
  - devfileregistries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - registry.devfile.io
  resources:
  - devfileregistries/status
  verbs:
  - get
